baseURL: https://bremen-ohne-bargeld.de/
languageCode: de-de
title: Bremen ohne Bargeld
params:
  short_title: Ohne Bargeld
  claim: Wo kann man in Bremen bargeldlos bezahlen?
  google_maps_api_key: AIzaSyB0yffafVx4X1L_YHC-w0D1VbvhP8or9cg
  google_analytics_id: G-NSKWQDPCVN
  cookiebot_id: 0503dc15-5bec-4734-a2d3-f6562d101654
